orientdb:
  connectionString: plocal:/home/bipedal/data/webthyme/orient
  user: admin
  password: admin

dataPath: /home/bipedal/data/webthyme

---
spring:
  profiles: test


orientdb:
  connectionString: memory:test
  user: admin
  password: admin

dataPath: /tmp/test